### ISSUE TITLE
[bug] Default MaxAge never applies

### ISSUE THREAD

**Issue by betawaffle** [gorilla/csrf#119]
**Describe the bug**

Ever since #38, the default MaxAge of 12 hours has not applied, because the [check](https://github.com/gorilla/csrf/pull/39/files#diff-ce2684ed9f2229737e48ae5c30ea04b6R130) ignores zero.

For us, the current behavior is fine, we actually want session lifetime, but the documentation should be updated, or the default should apply when there is no explicit option given. Perhaps a good idea would be to move the defaulting into `parseOptions` instead?

**Versions**

We found this behavior in v1.6.0, but the bug was introduced in #38.

**Steps to Reproduce**

Use `csrf.Protect` without specifying the `MaxAge` option.

**Expected behavior**

The `Max-Age` property on the cookie should be whatever the documentation says the default will be.

**Comment by betawaffle** [comment]
Sorry, I meant it was introduced in #39.

**Comment by elithrar** [comment]
Good catch.

Are you explicitly setting 0 in your application?

e.g. would this fix, if you pulled a fixed version, break your session
cookies?

**Comment by betawaffle** [comment]
We are now. We weren't before, and I have no idea what other people are doing. I suspect, based on what we did, that people who didn't specify it assumed the docs were correct, and that the default of 12 hours was in place.

**Comment by elithrar** [comment]
See https://github.com/gorilla/csrf/releases/tag/v1.6.1
