### ISSUE TITLE
[question] Downsides of `csrf.Path("/")`?

### ISSUE THREAD

**Issue by adiabatic** [gorilla/csrf#122]
After looking at all the [issues with "Path" in them](https://github.com/gorilla/csrf/issues?utf8=✓&q=is%3Aissue+Path), I've added `csrf.Path("/")` to the list of options I'm passing to `csrf.Protect()`. Now, when I POST to `/dashboard/bags/new/` from `/dashboard/` I don't get a CSRF-token-invalid error.

That said, [the documentation for Path](https://godoc.org/github.com/gorilla/csrf#Path) says that the default is the path the cookie was issued from. What, if anything, am I risking by having just the one CSRF cookie for `/`?

**Comment by elithrar** [comment]
The risk is primarily around conflicting with other parts of your
application - especially in multi-team architectures, or where you don’t
want to send cookies to certain backends.

Note that this is the default behavior of a cookie: not setting the Path
attribute has it default to the current path.

**Comment by adiabatic** [comment]
Good to know. Thanks!
