### ISSUE TITLE
Minor version Bump?

### ISSUE THREAD

**Issue by leononame** [gorilla/csrf#125]
Can you bump from v1.6.1 to v.1.6.2? We do not want to pin to the latest commit or @latest but would like to use SameSite=None for the cookie. This would help to just update to a new minor version.

**Comment by elithrar** [comment]
Sure - will do this weekend when back in town!

**Comment by elithrar** [comment]
Done! https://github.com/gorilla/csrf/releases/tag/v1.6.2
