### ISSUE TITLE
[question] csrf.Path("/") doesn't allow any path as expected

### ISSUE THREAD

**Issue by DDynamic** [gorilla/csrf#127]
I am trying to submit a POST request from URL `/` to URL `/tickets/new`. After setting `csrf.Path("/")`, I am still only able to POST to `/tickets/new` from `/tickets/new`. No other URL works.

```go
CSRF := csrf.Protect([]byte(os.Getenv("CSRF_KEY")), csrf.Secure(false), csrf.Path("/"))
err := http.ListenAndServe(":"+os.Getenv("PORT"), CSRF(r))
log.Fatal(err)
```
```
go version go1.13.4 windows/amd64
```
Let me know if there is any other information I need to provide. Thanks!

**Comment by elithrar** [comment]
Do you have any old cookies?
