### ISSUE TITLE
Using same csrf token for form and api calls from js side

### ISSUE THREAD

**Issue by crawter** [gorilla/csrf#128]
Hello, guys!

I'm developing an SPA application. Its uses an auth token and csrf token.

So have added an hidden field with csrf token to my index.html file.
Then, when i'm creating an http request i'm parsing value from this hidden field and add this token to request headers.

But each time it fails.

so. my server:

```
func NewServer() *Server {
	csrfMiddleware := csrf.Protect(
		[]byte("32-byte-long-auth-key"),
	)

	router := mux.NewRouter()
	fs := http.FileServer(http.Dir(server.config.StaticDir))

	apiController := consoleapi.NewController()
	apiRouter := router.PathPrefix("/api/v0/controller").Subrouter()
	apiRouter.Use(csrfMiddleware)
	apiRouter.HandleFunc("/api-call", apiController.Call).Methods(http.MethodPost)
	
	// handler for index.html
        router.PathPrefix("/").Handler(csrfMiddleware(http.HandlerFunc(server.appHandler)))

	server.server = http.Server{
		Handler:        router,
	}

	return &server
}

func (server *Server) appHandler(w http.ResponseWriter, r *http.Request) {
	var data struct {
		CsrfTag            template.HTML
	}

	data.CsrfTag = csrf.TemplateField(r)

        // executing index template 
	server.templates.index.Execute(w, data) 
}
```
So, my hidden input creates successfully with needed token value.

```
<input type="hidden" name="gorilla.csrf.Token" value="CSRF_TOKEN">
```

and each time before executing an api call i do next:

```
const csrfToken = (document.getElementsByName("gorilla.csrf.Token")[0] as any).value;
const headers: Record<string, string> = {
          ...
            'X-CSRF-Token': csrfToken,
        };
```

…

**Versions**
> Go version: go version go1.13.4 linux/amd64

> package version: v1.6.2
…

**Comment by elithrar** [comment]
What is the failure message?

**Comment by crawter** [comment]
http status 403

**Comment by crawter** [comment]
so, as i understand, token is not valid because of different sources.
i didn't pass token through api call like this:
```
func apiCall(w http.ResponseWriter, r *http.Request) {
    w.Header().Set("X-CSRF-Token", csrf.Token(r))
    ...
    w.Write(b)
}
```

i take it from the html hidden field

**Comment by elithrar** [comment]
You should also make sure your XHR/Fetch call includes the cookie when you
create the instance.

https://godoc.org/github.com/gorilla/csrf#FailureReason will give you the
detailed error message, as will the default response body.

**Comment by crawter** [comment]
@elithrar so, i receives next error

```"error": "CSRF token invalid"```

from the `csrf.FailureReason` function

**Comment by elithrar** [comment]
Your code above - this “apiCall” function - doesn’t make sense. Don’t do that. 

Your flow should be:

1. use the CSRF middleware
2. send the token in the request header of your JavaScript XHR call
3. Include the cookie in your XHR call as well - which you need to do explicitly. 

See the credentials section of this doc: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

**Comment by crawter** [comment]
@elithrar 
but what if user will refresh the page? 
in that case i will have to make new api call to get new csrf token.
Am i right?

**Comment by elithrar** [comment]
You should have logic on page load that reads the token and updates the request header, ready to go before you make any additional API calls.

**Comment by crawter** [comment]
oh. i see.

Thank you very much for your answers and your time!

Have a good day!
