### ISSUE TITLE
[question] Get 403 invalid csrf token occasionally 

### ISSUE THREAD

**Issue by danqing** [gorilla/csrf#129]
Thanks for the library!

I am having very occasional 403 invalid csrf token issue. Most of the time things go well, but sometimes when I POST I get 403, and if I refresh the page everything is fine again. Did I miss something obvious?

I'm using Gin, and my CSRF middleware is:

```go
func CSRF(secret string, secure bool) gin.HandlerFunc {
	return adapter.Wrap(csrf.Protect(
		[]byte(secret),
		csrf.Secure(secure),
	))
}
```

.. and I simply have an endpoint that returns the token:

```go
func (h *handler) csrfTokenHandler(c *gin.Context) {
	c.JSON(http.StatusOK, map[string]string{"token": csrf.Token(c.Request)})
}
```

Now on the client side, on page load I call the above endpoint to get the token, and I use it for subsequent POST requests. I have a basic wrapper function with the `xhr` npm package:

```js
function call(fn, opts, resolve, reject) {
  const options = {
    ...opts,
    useXDR: true,
    withCredentials: true
  }
  return fn(options, (err, resp, body) => {
    if (err || resp.statusCode > 299) {
      reject({ err, resp, body });
    } else {
      resolve(body);
    }
  });
}
```

where `opts` contains the `X-CSRF-Token` where applicable.

What may go wrong? Thanks!

**Comment by elithrar** [comment]
Can you inspect the error returned? Bad token? Expired?

**Comment by danqing** [comment]
The error is `Forbidden - CSRF token invalid`.

I've tried what mentioned by some other issues but so far no success..

**Comment by elithrar** [comment]
Can you also inspect
https://godoc.org/github.com/gorilla/csrf#FailureReason - it sounds like
you may have a stale cookie.

**Comment by danqing** [comment]
Thanks for the pointer! It turns out I have 2 concurrent GET requests, one overriding the cookie set by the other. I've since fixed the issue.
