### ISSUE TITLE
[question] Why should we pass the CSRF.Token in Header for a web Application and not in Cookie

### ISSUE THREAD

**Issue by Justin2997** [gorilla/csrf#138]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

I have a working implementation with your example for Javascript Application with React. Because React is served when build I can not use the input system to get the token. I have to get it from the header and store it in a cookie to send it in the header of my next call. Is this a good practice? If yes, why did the handler do not set also set a cookie if we pass the good option? 

Thanks a lot ! 

**Versions**
> Go version: `go version`

go version go1.14.2 darwin/amd64

> package version: run `git rev-parse HEAD` inside the repo

Last version

**Comment by Justin2997** [comment]
Also, calling multiple time csrf.token generates a new token with the private key. Did that expose me to an attack if the attacker has multiple token forms multiple call ? Thanks a lot !

**Comment by elithrar** [comment]
An attacker with multiple tokens cannot infer the shared key used to
generate tokens.

The “key” in the mask is a per-request nonce used to make using the BREACH
attack harder to execute.

**Comment by Justin2997** [comment]
Ok perfect! So that will be a correct implementation to only use Cookie to validate and not the header of the request? Thanks.

**Comment by elithrar** [comment]
Provided you can use the cookie across domains, yes. In many cases you can't, which is why the header option exists.
