### ISSUE TITLE
[question] X-Csrf-Token is empty in Response headers (Secure is off)

### ISSUE THREAD

**Issue by austincollinpena** [gorilla/csrf#139]
Yes, my "secure" setting is set to false :) 

Using ```github.com/gorilla/csrf v1.7.0``` and ```go 1.14```

I have the set up:
app.localhost.com calls api.localhost.com

Problem: Stated in title, my Response headers look like this:
```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://app.localhost.com
Access-Control-Expose-Headers: *
Content-Length: 0
Date: Mon, 10 Aug 2020 17:07:37 GMT
Set-Cookie: testCookie=there; Domain=localhost.com; Expires=Mon, 10 Aug 2020 17:37:37 GMT; HttpOnly
Set-Cookie: _gorilla_csrf=MTU5NzA3OTI1N3xJamRvUWxwdVlVSmlaRWRqVWpkSmJVRldNRzFtVFcxUmNEbEhSQ3RZVGs5aFYyZ3hRa1JrYzNCQk5EQTlJZ289fDhJXLZGYzxZ9ctPZcVEiV3JvgsZ9VVc-55nWhOcucz-; Domain=localhost.com; Expires=Tue, 11 Aug 2020 05:07:37 GMT; Max-Age=43200; HttpOnly; SameSite=Lax
Vary: Origin
X-Csrf-Token:  // Problem right here
Xcrsf: hello!  // Shows that I can set a header
```
My (pared down) server code looks like this:

```go
func main() {

	r := chi.NewRouter()
	r.Use(middleware.Recoverer)
	r.Use(middleware.Logger)
	r.Use(middleware.Timeout(30 * time.Second))
	r.Use(httprate.LimitByIP(100, 1*time.Minute))

	r.Use(cors.New(cors.Options{
		AllowedOrigins:   []string{"http://app.localhost.com", "http://api.localhost.com"},
		AllowCredentials: true,
		Debug:            true,
		AllowedHeaders:   []string{"Content-Type", "Sentry-Trace", "X-CSRF-Token"},
		//AllowedHeaders:   []string{"*"},
		MaxAge:           300,
		ExposedHeaders: []string{"*"},
	}).Handler)
	r.Use(AddUserIDToCTX())

	port := os.Getenv("PORT")
	if port == "" {
		port = defaultPort
	}

	csrfMiddleware := csrf.Protect([]byte("AB4F63F9AC65152575886860DDE480A1"),
		csrf.TrustedOrigins([]string{"localhost.com"}),
		csrf.Secure(false),
		csrf.ErrorHandler(http.HandlerFunc(func(res http.ResponseWriter, req *http.Request) {
			fmt.Printf("failed CSRF - %s", csrf.FailureReason(req))
		})),
	)
	r.Use(csrfMiddleware)

	r.Route("/graphql", func(r chi.Router) {
             // graphql stuff
	})

	panic(http.ListenAndServe("0.0.0.0:8089", appdb.SessionManager.LoadAndSave(r)))
}
```

And then I set the header in my session middleware:

```go
//// Middleware decodes the share session cookie and packs the session into context
func AddUserIDToCTX() func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {

			// Add CSRF Token on each request
			w.Header().Set("X-CSRF-Token", csrf.Token(r))
			w.Header().Set("xcrsf", "hello!")
			// Session stuff below
		})
	}
}
```

Any idea why my header won't get set? Should I share my Traefik config?

Ps. Love listening to the Gorilla team on the Go Time podcast!

**Comment by austincollinpena** [comment]
Anyone have a second to take a look , or point me in the right direction?

**Comment by elithrar** [comment]
Is your userID middleware running before the CSRF middleware has created a token?

Chi's middleware ordering may be at play here. Put `csrf.Protect` first.

**Comment by austincollinpena** [comment]
I think I still have a fundamental misunderstanding that's causing an issue. In order to authenticate a crsf request, do I need to first retrieve a token? So does that mean I need to run a REST request separate of my graphql to an unprotected endpoint?

What I just did was this:

```go
func CRSFAdder(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("X-CRSF-Token", csrf.Token(r))
		next.ServeHTTP(w, r)
	})
}
```

```go

// Add the middleware that adds the crsf token to the header
	r.Use(CRSFAdder)
	csrfMiddleware := csrf.Protect([]byte("AB4F63F9AC65152575886860DDE480A1"),
		csrf.TrustedOrigins([]string{"localhost.com"}),
		csrf.Domain("localhost.com"),
		csrf.Secure(false),
		csrf.ErrorHandler(http.HandlerFunc(func(res http.ResponseWriter, req *http.Request) {
			fmt.Printf("failed CSRF - %s", csrf.FailureReason(req))
		})),
	)
// THEN, call the csrf.protect
	r.Use(csrfMiddleware)
// Finally, add the user ID to the context
	r.Use(AddUserIDToCTX())
```

My Response Headers still show an empty crsf token. Do you think that I have a misunderstanding of how to use the library? Or is there something else at play?

**Comment by elithrar** [comment]
I think you might misunderstand the library.

- are your site vs REST API on the same domain? Different?
- does your browser have the _gorilla_csrf cookie set?
- can you post the full output of the XHR request and response from the
console?

**Comment by austincollinpena** [comment]
>- are your site vs REST API on the same domain? Different?
My front end is on app.localhost.com, and my backend is api.localhost.com, which is appropriate for this use case, yes?

> does your browser have the _gorilla_csrf cookie set?
Yes.

> - can you post the full output of the XHR request and response from the console?

**Fetch Request**
```
General:
Request URL: http://api.localhost.com/graphql/
Request Method: POST
Status Code: 200 OK
Remote Address: 127.0.0.1:80
Referrer Policy: no-referrer-when-downgrade

Response Headers:
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://app.localhost.com
Access-Control-Expose-Headers: *
Content-Length: 0
Date: Mon, 17 Aug 2020 21:54:51 GMT
Vary: Origin
X-Crsf-Token: 
X-Ratelimit-Limit: 100
X-Ratelimit-Remaining: 99
X-Ratelimit-Reset: 1597701300

Request Headers:

POST /graphql/ HTTP/1.1
Host: yeet.localhost.com
Connection: keep-alive
Content-Length: 286
accept: */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
content-type: application/json
Origin: http://app.localhost.com
Referer: http://app.localhost.com/app/create/editor
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,la;q=0.8
Cookie: _gorilla_csrf=MTU5NzY4NzMxN3xJazlhVDBrME9HNUlVaXQwUkdGTGNUWkZUMGxUTVV0RlZFeHRhRXBGV1dSck1GYzFkVzAyYzBoWVoxRTlJZ289fIBJJM47KWR9f9nAzp12eBJNSpWGXAB4ODT-Q95plxw0; session=Dh4c5MLH7oRMUP1enQ8tJ-vGLMaF1jqwN82BrDVgnOE; mp_314c3e39649f910d149c8979b545ea37_mixpanel=%7B%22distinct_id%22%3A%20%22austincollinpena%40gmail.com%22%2C%22%24device_id%22%3A%20%22173fda3fedc476-0662b42c0afef5-3323767-1fa400-173fda3fedd975%22%2C%22%24initial_referrer%22%3A%20%22http%3A%2F%2Fapp.localhost.com%2Fapp%2Fcreate%2Feditor%22%2C%22%24initial_referring_domain%22%3A%20%22app.localhost.com%22%2C%22%24user_id%22%3A%20%22austincollinpena%40gmail.com%22%7D

Request Payload
{"operationName":"checkIfPageIsValid","variables":{"input":{"domain":"https://equipomedia.com","url":"https://www.equipomedia.com/s"}},"query":"mutation checkIfPageIsValid($input: urlAndRootDomain) {\n  doesThisWebsiteExist(input: $input) {\n    page\n    id\n    __typename\n  }\n}\n"}

```

I also get a new error which is ```[cors] 2020/08/17 21:55:14   Actual request no headers added: missing origin
``` when adding the csrf token middleware.

**Comment by austincollinpena** [comment]
I feel like I'm dumping too much into this question and expecting you to fix it. Is there something I can provide or extra steps I can take that would help?

**Comment by elithrar** [comment]
(I can keep helping, but not on an hourly basis - I have not had time to
look at your latest answer)

Can you confirm the CSRF middleware runs BEFORE your userID middleware now?

**Comment by austincollinpena** [comment]
I don't expect timely responses, I appreciate the help!

> Can you confirm the CSRF middleware runs BEFORE your userID middleware now?

Yes it does.

**Comment by ethangk** [comment]
> I think I still have a fundamental misunderstanding that's causing an issue. In order to authenticate a crsf request, do I need to first retrieve a token? So does that mean I need to run a REST request separate of my graphql to an unprotected endpoint?
> 
> What I just did was this:
> 
> ```go
> func CRSFAdder(next http.Handler) http.Handler {
> 	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
> 		w.Header().Set("X-CRSF-Token", csrf.Token(r))
> 		next.ServeHTTP(w, r)
> 	})
> }
> ```
> 
> ```go
> // Add the middleware that adds the crsf token to the header
> 	r.Use(CRSFAdder)
> 	csrfMiddleware := csrf.Protect([]byte("AB4F63F9AC65152575886860DDE480A1"),
> 		csrf.TrustedOrigins([]string{"localhost.com"}),
> 		csrf.Domain("localhost.com"),
> 		csrf.Secure(false),
> 		csrf.ErrorHandler(http.HandlerFunc(func(res http.ResponseWriter, req *http.Request) {
> 			fmt.Printf("failed CSRF - %s", csrf.FailureReason(req))
> 		})),
> 	)
> // THEN, call the csrf.protect
> 	r.Use(csrfMiddleware)
> // Finally, add the user ID to the context
> 	r.Use(AddUserIDToCTX())
> ```
> 
> My Response Headers still show an empty crsf token. Do you think that I have a misunderstanding of how to use the library? Or is there something else at play?

@austincollinpena I imagine this has long been solved, but it looks like the wrong header could be getting set:

```go
w.Header().Set("X-CRSF-Token", csrf.Token(r))
instead of
w.Header().Set("X-CSRF-Token", csrf.Token(r))
```
