### ISSUE TITLE
Does gorilla-csrf really provide more security?

### ISSUE THREAD

**Issue by robojones** [gorilla/csrf#143]
**Describe the problem you're having**
I am trying to understand what problem gorilla-csrf solves.
As far as I understand CSRF is when an attacker executes cross site requests when I visit their website. For example, when I am logged into an online shop, the attacker site could try to send an order form without my knowledge.
I understand that this library makes that impossible for them but wouldn't it be easier if the online shop just verified the `Origin` or `Referer` header?

Thanks in advance for any input :smiley:

**Comment by elithrar** [comment]
Please take a look at
https://owasp.org/www-community/attacks/csrf and
https://portswigger.net/web-security/csrf

Validating the Origin / Referer headers - which may not be present in all
cases, and certainly not for a cross-domain POST over HTTPS - does not
protect you from CSRF attacks.

**Comment by robojones** [comment]
Thanks for clarifying that @elithrar 👍

**Comment by steebchen** [comment]
I'm not sure if that's true for what @robojones suggests.
If your API just accepts POST requests, it looks like checking for the origin header seems to be sufficient in 2020 onward; assuming you use it in combination with SameSite=Strict cookies.

Also see:

https://security.stackexchange.com/questions/158045/is-checking-the-referer-and-origin-headers-enough-to-prevent-csrf-provided-that

**Comment by ScottyFillups** [comment]
@steebchen why is using SameSite=Strict cookies a requirement? Isn't reading the Origin header enough?

**Comment by robojones** [comment]
@ScottyFillups
> why is using SameSite=Strict cookies a requirement? Isn't reading the Origin header enough?

`SameSite=Strict` on cookies just provides an additional layer of security.
I did look into this and checking the `Origin` header should already to prevent CSRF.

> Doesn't that mean the `Origin` header is sent for all cross-domain POSTs over HTTPS? As for GET and HEAD, as long as you ensure those methods don't mutate state, you should be fine to skip the origin check, right?

Yup
