### ISSUE TITLE
Declare an exported type for option functions.

### ISSUE THREAD

**Issue by garyburd** [gorilla/csrf#15]
func Option func(*csrf)
    func Protect(authKey []byte, opts ...Option) func(http.Handler) http.Handler
    func CookieName(name string) Option
    ...

Benefits:

- Improved documentation organization. All functions returning Option will be listed under the Option type.
- Application flexibility. This change will allow applications to declare and construct a slice of options separate from the implicit slice constructed by the variadic call.

**Comment by davecheney** [comment]
SGTM.

**Comment by elithrar** [comment]
I've had this planned for a little while - will try to push the change up
tonight. Thanks @garyburd.

**Comment by elithrar** [comment]
Done. Docs looking much better now and makes it easier for newcomers to grok the API.

<img width="333" alt="screen shot 2015-10-26 at 7 50 47 pm" src="https://cloud.githubusercontent.com/assets/18544/10728226/ff836d3c-7c1a-11e5-9444-c2271eb8b695.png">
