### ISSUE TITLE
CSRF middlware is not usable with go gin

### ISSUE THREAD

**Issue by rew1nter** [gorilla/csrf#160]
**Describe the bug**
> I was trying to implement CSRF middleware with go gin but it fails 

…

**Versions**
> Go version: ` go1.17.1 windows/amd64`

…

**Steps to Reproduce**
> try to register a middlware in go gin and run the code
…

**Code Snippets**
![Screenshot_1013](https://user-images.githubusercontent.com/64508791/144583959-80f5b337-8ec8-45ed-bc90-a4ea7856617f.png)

**Comment by bstpierre** [comment]
gin uses a different function type for middleware, you need to use an adapter. See this comment for a solution: https://github.com/gorilla/csrf/issues/78#issuecomment-524144965
