### ISSUE TITLE
FieldName option documentation is incorrect. 

### ISSUE THREAD

**Issue by cudevmaxwell** [gorilla/csrf#18]
`FieldName` doesn't set csrf.TemplateTag, it sets `csrf.opts.FieldName`

Corrected docs:

    // FieldName allows you to change the name value of the hidden <input> field
    // generated by csrf.TemplateField. The default is "gorilla.csrf.Token"
    ....

**Comment by elithrar** [comment]
@cudevmaxwell Thanks for picking this up - I'd changed the docs to reflect the (incorrect) mention of `{{ .csrfField }}` instead of the other way around.
