### ISSUE TITLE
TemplateField doesn't seem to work with custom FieldName

### ISSUE THREAD

**Issue by pqyptixa** [gorilla/csrf#19]
I couldn't make TemplateField() work when calling FieldName().
In https://github.com/gorilla/csrf/blob/master/helpers.go#L54 , shouldn't cs.opts.FieldName be used instead of fieldName?
I can't find the place where fieldName is set to cs.opts.FieldName: https://github.com/gorilla/csrf/search?utf8=%E2%9C%93&q=fieldName

**Comment by elithrar** [comment]
Hi @pqyptixa - `TemplateField` doesn't work with a custom fieldname - it only works with the default. `TemplateField`, as a function, doesn't have a way to access `cs.opts.FieldName`. I'd have to change the package-level variable—which would break the ability to have multiple CSRF instances. 

It's primarily meant as a convenience function to help you use the library "out of the box". Note that calling `FieldName("somecustomfieldname")` during initialization *does* still take affect, as it will change what value is read by the library on a form submission (POST/PUT/PATCH).

To *set* a custom field name you can:

```go
    t.ExecuteTemplate(w, "signup_form.tmpl", map[string]interface{
        // Where myFieldName has also been via csrf.FieldName when creating the CSRF handler
        csrf.TemplateTag: fmt.Sprintf(`<input type="hidden" name="%s" value="%s">`,
		"myFieldName", Token(r))
    })
```

Hope that helps clear things up.

**Comment by pqyptixa** [comment]
Ahh, OK, thank you for explaining and thanks for your work. I guess I should have paid more attention to the docs :)
