### ISSUE TITLE
CSRF 处理 multipart/form-data 的问题

### ISSUE THREAD

**Issue by panjunjie** [gorilla/csrf#2]
当时使用 PathPrefix 的时候，CSRF 会失效，比如以下代码：

CSRF := csrf.Protect(
            []byte("a-32-byte-long-key-goes-here"),
    )

router := mux.NewRouter()
router.HandleFunc("/front/", controller.FontIndex)

adminRoutes := mux.NewRouter()
adminRoutes.HandleFunc("/admin/form", controller.AdminForm)

router.PathPrefix("/admin").Handler(negroni.New(
    negroni.NewRecovery(),
    middleware.NewCheckLogin(),
    negroni.Wrap(adminRoutes),
))

n := negroni.New(
    negroni.NewRecovery(),
)

n.UseHandler(CSRF(router))

log.Fatal(http.ListenAndServe(":3001", n))

访问 http://domain/front ,CSRF是可以用的，但如果访问 http://domain/admin/form ，这时 CSRF 会失效。

**Comment by elithrar** [comment]
I'm not quite sure what your problem is, but I didn't have any issues running your program after replacing the handlers with basic stubs:

```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/codegangsta/negroni"
	"github.com/gorilla/csrf"
	"github.com/gorilla/mux"
)

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Index! %v", csrf.Token(r))
}

func Form(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Admin form! %v", csrf.Token(r))
}

func main() {
	CSRF := csrf.Protect(
		[]byte("a-32-byte-long-key-goes-here"),
	)

	router := mux.NewRouter()
	router.HandleFunc("/front", Index)

	adminRoutes := mux.NewRouter()
	adminRoutes.HandleFunc("/admin/form", Form)

	router.PathPrefix("/admin").Handler(negroni.New(
		negroni.NewRecovery(),
		//middleware.NewCheckLogin(),
		negroni.Wrap(adminRoutes),
	))

	n := negroni.New(
		negroni.NewRecovery(),
	)

	n.UseHandler(CSRF(router))

	log.Fatal(http.ListenAndServe(":3001", n))
}
```

Tests:

```sh
~/Desktop curl http://localhost:3001/front
Index! lb34ScJ8x6HXzV+G/eWAF6DIHFCdKAu0XPDR34u6pdJ/47mxU/Ry+KBoA2k5kgAR9ygV9EVKcCxv2YoG9Oz6Iw==%
~/Desktop curl http://localhost:3001/admin/form
Admin form! rfVe0ZzFYny1rKGPdLmj4vQOFH5un4q3kMTQPYLLxYzvEXAQ1OZfuLqeijTBeSsW81CkZp7YBAu46joCvKpW7Q==%
```

If you're still having issues, can you show more of your code? There is a language barrier between us but the code may help explain.

**Comment by panjunjie** [comment]
好的，感谢你的帮忙，我现在先自己检查一下问题，似乎不是 github.com/gorilla/csrf 的问题。

**Comment by elithrar** [comment]
No problem. Let me know if you run into other issues.

**Comment by panjunjie** [comment]
Ok,thanks.

**Comment by panjunjie** [comment]
这几天，排查了一下问题，现在发现：如果 form 带 enctype="multipart/form-data"，问题就出现了，提示： Forbidden - CSRF token invalid，这种情况算是 bug 吧？

**Comment by panjunjie** [comment]
@elithrar  我这几天，排查了一下问题，现在发现：如果 form 带 enctype="multipart/form-data"，发生异常： Forbidden - CSRF token invalid，这种情况算是 bug 吗？

**Comment by panjunjie** [comment]
引用你的代码做了加`enctype="multipart/form-data"`修改，出现上面说的问题了。
`
package main

import (
    "fmt"
    "log"
    "net/http"
    "text/template"

    "github.com/codegangsta/negroni"
    "github.com/gorilla/csrf"
    "github.com/gorilla/mux"
)

var form = `
<html>
<head>
<title>Sign Up!</title>
</head>
<body>
<form method="POST" action="/admin/form" accept-charset="UTF-8">
<input type="text" name="name">
<input type="text" name="email">

{{ .csrfField }}
<input type="submit" value="Sign up!">
</form>
</body>
</html>
`

var t = template.Must(template.New("signup_form.tmpl").Parse(form))

func Index(w http.ResponseWriter, r *http.Request) {
    t.ExecuteTemplate(w, "signup_form.tmpl", map[string]interface{}{
        csrf.TemplateTag: csrf.TemplateField(r),
    })
}

func Form(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "%v\n", r.PostForm)
}

func main() {
    CSRF := csrf.Protect(
        []byte("a-32-byte-long-key-goes-here"),
    )

    router := mux.NewRouter()
    router.HandleFunc("/front", Index)

    adminRoutes := mux.NewRouter()
    adminRoutes.HandleFunc("/admin/form", Form)

    router.PathPrefix("/admin").Handler(negroni.New(
        negroni.NewRecovery(),
        //middleware.NewCheckLogin(),
        negroni.Wrap(adminRoutes),
    ))

    n := negroni.New(
        negroni.NewRecovery(),
    )

    n.UseHandler(CSRF(router))

    log.Fatal(http.ListenAndServe(":3001", n))
}
`

**Comment by elithrar** [comment]
I've updated the package to support `multipart/form-data`. Run the following to grab the latest version:

```sh
go get -u github.com/gorilla/csrf
```

Hope that solves it!

**Comment by panjunjie** [comment]
现在发生 http status 400 错误，我的 web application 使用了 https://github.com/mholt/binding 处理 form 表单，结果 binding 提示：[{"classification":"DeserializationError","message":"http: multipart handled by ParseMultipartForm"}]。

**Comment by panjunjie** [comment]
现在 binding 和 csrf  结合使用，出现了问题。还不知道是哪个环节出问题。

**Comment by elithrar** [comment]
Quick update: I'm looking into ways to solve this for package users. The
problem is that the CSRF package must call `r.ParseMultipartForm` in order
to retrieve the CSRF token, but this means that downstream handlers end up
with an empty request body.

The solution may be to provide an option for copying the request body prior
to calling ParseForm and then re-populating it afterwards.

**Comment by panjunjie** [comment]
恩，好的。如果有个例子就更好了。

**Comment by rand99** [comment]
Could you please implement a verification method we can use within a handler? 
gorilla/csrf doesn't work with r.MultipartReader
solution would be not to use the CSRF middleware and instead check if the token is ok in the handler for multi file uploads - i think
