### ISSUE TITLE
Support per-session tokens?

### ISSUE THREAD

**Issue by kliron** [gorilla/csrf#27]
My understanding is that the current implementation generates unique per-request tokens. I find this impractical to work with in complex clients where multiple concurrent AJAX requests are generated. I don't really see why generating per-request tokens is any more secure than generating per-session ones. If a session is highjacked the leakage of the CSRF token is the *least* of my concerns.

**Comment by elithrar** [comment]
The base token persists for as long as the cookie does, but the token is
masked per request to mitigate against the BREACH attack.

Since the base token does not change, multiple concurrent AJAX requests (or
browser tabs) do not break CSRF checks.

**Comment by kliron** [comment]
Thank you for the clarification. I should have read the docs more thoroughly. Closing this.
