### ISSUE TITLE
Angular SPA issue

### ISSUE THREAD

**Issue by kevana** [gorilla/csrf#29]
I'm trying to add csrf protection to an Angular SPA that often has multiple API requests in flight concurrently.

[PR on DockerUI](https://github.com/crosbymichael/not-dockers-ui/pull/201)

From [here](http://stackoverflow.com/questions/36348761/forbidden-csrf-token-invalid-with-gorilla-csrf-and-angular) originally.

**Comment by kevana** [comment]
All non-GET requests are coming back with a 403:

## Initial pageload (private browsing mode):

<img width="1102" alt="screen shot 2016-04-01 at 10 25 49 am" src="https://cloud.githubusercontent.com/assets/981551/14211525/2e60dfae-f7f4-11e5-8d8b-ea1147261647.png">

```
2016/04/01 15:20:31 Request starting: /
2016/04/01 15:20:31 Unable to find session cookie _gorilla_csrf
```
Cookie value before POST:
<img width="1243" alt="screen shot 2016-04-01 at 10 21 01 am" src="https://cloud.githubusercontent.com/assets/981551/14211388/7d0fbd42-f7f3-11e5-92f5-2d5adfa0d069.png">

## POST:
<img width="1100" alt="screen shot 2016-04-01 at 10 24 19 am" src="https://cloud.githubusercontent.com/assets/981551/14211478/f8cd8662-f7f3-11e5-99d6-54c9cef08e36.png">
```
2016/04/01 15:22:34 Request starting: /dockerapi/volumes/create
2016/04/01 15:22:34 Cookie:MTQ1OTUyNDAzMXxJbEZNVWxwNlRqZGFXbU5sTUhsMlVsQkZRVFJqY1hVemRVaFZTWGRSY0ZRemFYaHlWM2xrVUU1VmRVazlJZ289fEulnY7Y753RqYuQOMimtxXhBMk3JcC7hG27q2Qb2j6l
2016/04/01 15:22:34 Header:MTQ1OTUyNDAzMXxJbEZNVWxwNlRqZGFXbU5sTUhsMlVsQkZRVFJqY1hVemRVaFZTWGRSY0ZRemFYaHlWM2xrVUU1VmRVazlJZ289fEulnY7Y753RqYuQOMimtxXhBMk3JcC7hG27q2Qb2j6l
2016/04/01 15:22:34 Request ending
```

**Comment by elithrar** [comment]
The only time you get a "CSRF token invalid" is if the token in the request does not match the token in the header. From what you've posted this doesn't look like the case.

This can happen if the store can't read the cookie (e.g. the cookie fails authentication), generates a fresh token, and this token doesn't match.

Can you trash all of your for this domain, use a static `authKey` (from a config file or ENV var) and try again?

**Comment by kevana** [comment]
Set a static authKey and still seeing the same behavior: 

<img width="1098" alt="screen shot 2016-04-01 at 11 49 53 am" src="https://cloud.githubusercontent.com/assets/981551/14213917/fa88ec88-f7ff-11e5-9bad-a883c0161429.png">

**Comment by elithrar** [comment]
Is there a simple way for me to run your application locally? Otherwise I'll need to tie together a quick demo server with some AJAX to replicate what Angular is doing (get_cookie => ajax.headers)

**Comment by kevana** [comment]
It requires Docker, once you have that:
```
git clone https://github.com/crosbymichael/not-dockers-ui.git
cd not-dockers-ui
npm install
grunt run
```
That's my preferred method for making changes to the Angular part. Compiling the golang part is really slow with the golang-builder image but you can run the binary outside of docker and point it at the API endpoint inside docker:
```
# First, run the above steps to get DockerUI running with access to the Docker socket, then:
go build .
cp not-dockers-ui dist/
cd dist
./not-dockers-ui -e http://192.168.99.100:9000/dockerapi
```

**Comment by elithrar** [comment]
OK, great. I want to add some logging to gorilla/csrf to confirm my
suspicions and then have your Angular app hit it.

Might not have a response until end of day, but hopefully we can solve it.

**Comment by kevana** [comment]
No worries, I'm also digging into the server side, at first glance it looks like `requestToken := unmask(cs.requestToken(r))` at [csrf.go:237](https://github.com/gorilla/csrf/blob/master/csrf.go#L237) is coming back empty, not sure why yet.

**Comment by elithrar** [comment]
Double check that your header name doesn't contain any invisible
characters/spaces/etc - Header.Get() doesn't do any cleanup.

**Comment by kevana** [comment]
Looks like it found the header by name, base64 decoding failed:
```
2016/04/01 13:21:55 requestToken() header: MTQ1OTUzMjk4NHxJbkJ0YVZvMFJEWktkRGxqUWpCdlVDOHZlRVl6Y0dkU2RVVlBTR1Z4TDJ4dWRsQXlSMUZaZVdVeVIyYzlJZ289fKvlLUxzV6wk9uGA2eS3BXz25hA_n64XauTH7Xek2LFI
2016/04/01 13:21:55 illegal base64 data at input byte 127
```
I wonder if I'm double-encoding something by accident

**Comment by elithrar** [comment]
That is the underscore - which is part of base64 URLEncoding. gorilla/csrf
uses base64.StdEncoding (which uses "/" instead of "_")

**Comment by kevana** [comment]
What does that mean?

**Comment by elithrar** [comment]
It means that something is modifying the base64 encoding (which is why it
fails) - I'm not sure why yet.

**Comment by kevana** [comment]
I edited the above comment. Looks like securecookie encodes with UrlEncoding, csrf tries to decode with StdEncoding?

**Comment by elithrar** [comment]
Which is fine, because gorilla/securecookie has already decoded it by the
time gorilla/csrf gets it (and if it didn't, this would break for everyone,
everywhere).

**Comment by elithrar** [comment]
@kevana Derp, here's the answer.

1. Angular is copying the cookie into the header.

```sh
$httpProvider.defaults.xsrfCookieName = '_gorilla_csrf';
$httpProvider.defaults.xsrfHeaderName = 'X-CSRF-Token';
```

2. The cookie is encoded; when the tokens are compared you actually end up with <decoded cookie> vs. <encoded cookie value in header>

3. What you really want to do is detailed in the docs: https://github.com/gorilla/csrf#json-responses - *write* a response header with the value, and have Angular capture that into local storage and send it back in a request header.

3.1 Alternatively, if your Go application is generating the base template for your Angular app, you can put the CSRF token in a `<meta name="csrf.token" content=".csrfToken">` item in the `<head>`, and have Angular read that value and send it back in the `X-CSRF-Token` header on each request (this is how Rails does it).

**Comment by kevana** [comment]
Didn't realize the cookie wasn't the token, got it working. Thanks for the help!
