### ISSUE TITLE
Keep getting: Forbidden - CSRF token invalid - using example

### ISSUE THREAD

**Issue by fmpwizard** [gorilla/csrf#30]
Hi,

I must be doing something really wrong but running the example from 
http://www.gorillatoolkit.org/pkg/csrf

keeps giving me `Forbidden - CSRF token invalid`

the only changed I made to the example was to use

`csrf.Protect([]byte("keep-it-secret-keep-it-safe-----"))(r))`

in the post request,  I see the name, email fields being submitted, and also

`gorilla.csrf.Token: XrNHtAeI5BWdNniozRfxNXjv65myi/Lo6GhCqED1cHXLgpYjSJmyROznxCqjwvB9sRZiiGNMbqkIAtBwPIvQcw==`

I added some logging to

https://github.com/gorilla/csrf/blob/master/csrf.go#L181

and I see that `realToken` is always `[]` 

I'm running this on http://localhost:8000/ and made sure to delete all cookies between runs in case I was in some kind of bad state

Thank you.

**Comment by fmpwizard** [comment]
of course, after submitting this I found out I needed to make two changes, one was the key, the other was:

`csrf.Protect([]byte("keep-it-secret-keep-it-safe-----"), csrf.Secure(false))(r))`

it could help to have a note on the docs (I actually found the note on your blog after googling again).

Thanks

**Comment by elithrar** [comment]
Are you setting csrf.Secure(false) in development? Cookies are only sent
over HTTPS by default.

**Comment by fmpwizard** [comment]
Now that I pass `csrf.Secure(false)` the sample is working ok (and will make it a flag for dev mode only). Thanks. I'll close this ticket now

**Comment by wayneashleyberry** [comment]
I've also just run into this problem, maybe it could be cleared up in the documentation?

**Comment by elithrar** [comment]
This is currrently documented in-line with the example code. Where else
would you like to see it / how can it be made clearer?

**Comment by fmpwizard** [comment]
I see it on the README, which is great, maybe adding it inline to the examples found on http://www.gorillatoolkit.org/pkg/csrf is all that is needed now

**Comment by wayneashleyberry** [comment]
Yeah, the readme mentions the use of `csrf.Secure(false)` in the first example whereas the website only really mentions it under the method documentation.

**Comment by wayneashleyberry** [comment]
Added the same comment from the readme to the docs here https://github.com/gorilla/csrf/pull/44, that would hopefully prevent this from happening again :)

**Comment by elithrar** [comment]
Closed via https://github.com/gorilla/csrf/pull/44
