### ISSUE TITLE
how to invalidate a token?

### ISSUE THREAD

**Issue by fmpwizard** [gorilla/csrf#31]
Hi,

I just started testing this library and noticed that I can reuse a token for the same form. Is there a way to invalidate the tokens already submitted?

**Comment by elithrar** [comment]
No, as invalidating tokens would break tabs/multiple windows.

Re-using the token is safe, and you can set the cookie with a short expiry
if you have any concerns.

**Comment by fmpwizard** [comment]
What are my options on this scenario:

1- user A logins into my site from a public computer
2- leaves the computer before he/she logs out
3- a user B goes on the same computer
4- user B reads the cookie and saves it as a curl request
5- user A realizes this, so he/she logs out that other location (like you can do in gmail, etc)
6- but user B can still use the saved cookie for as long as they want

at least this is what I'm seeing in my local tests

Thanks

**Comment by elithrar** [comment]
CSRF tokens are not associated with login sessions, so possession of another users' token would not allow you to masquerade as them.

If you did have another users' cookie, you wouldn't be able to perform a CSRF attack as you can't inject cookies into their browser without a full-fledged MitM attack (under which case CSRF is no longer required).

**Comment by fmpwizard** [comment]
ah, so, the reason why the request I was sending using curl kept passing the token validation is because I was sending the same cookie that your library uses and the matching token?

**Comment by elithrar** [comment]
It passes because you have a valid cookie. Cookies are generated per user
(well, browser session).

**Comment by fmpwizard** [comment]
Thanks for all the details, I'll close this now
