### ISSUE TITLE
Allow custom cookie name

### ISSUE THREAD

**Issue by dre1080** [gorilla/csrf#4]
Could you add support for this?

**Comment by elithrar** [comment]
Shouldn't be too hard. What's the use case—legacy service elsewhere?

**Comment by dre1080** [comment]
Just as a preference.

**Comment by elithrar** [comment]
See https://github.com/gorilla/csrf/pull/5

Just run `go get -u github.com/gorilla/csrf` and then call the option function - e.g.

```go
  CSRF := csrf.Protect(
            []byte("a-32-byte-long-key-goes-here"),
            csrf.CookieName("yourcookiename"),
)
```

Stating the obvious: make sure the name has no spaces/backslashes/commas/semicolons and you won't run into trouble.
