### ISSUE TITLE
Generate token without being protected?

### ISSUE THREAD

**Issue by eriklott** [gorilla/csrf#40]
We're working with a static SPA and a JSON api backend written in go.

When an authentic set of credentials are posted to /authenticate, a secure http-only cookie is set (for authentication purposes), and - hopefully - a CSRF token is returned in the json body. The SPA stores the csrf token, and sends it with each subsequent api request in the header.

The  /authenticate handler should not be CSRF protected, yet it needs to return a CSRF token. Can gorilla csrf do this? I can't seem to generate a token in a handler without that handler also being protected...

Thoughts?

**Comment by elithrar** [comment]
I don't think this is immediately possible for POST requests (only non-idempotent endpoints return tokens) without doing two requests (a GET in the background, and then a POST to `/authenticate`).

Depending on how you're serving your static content/initial HTML view however, you could also wrap the handler serving your `index.html` (that you use to bootstrap your SPA) with `csrf.Protect`, and use `html/template` to inject the token into a `<meta>` tag. This would work today and be pretty seamless, but depends on you not serving your static assets from another application.

**Comment by eriklott** [comment]
Okay, thanks for confirming Matt.
