### ISSUE TITLE
Setting the X-CSRF-Token header does not work on App Engine

### ISSUE THREAD

**Issue by sprt** [gorilla/csrf#41]
Test case: [csrf-gae-bug.zip](https://github.com/gorilla/csrf/files/364763/csrf-gae-bug.zip)

Repro:

$ /path/to/go-gae-sdk/goapp serve .
Click the submit button
=> Output: Forbidden - CSRF token invalid

Passing the token in a hidden field works fine.

Note: tested with SDK version 1.9.36 as newer versions have [a bug](https://code.google.com/p/google-cloud-sdk/issues/detail?id=521) preventing me from running any code at all.

**Comment by elithrar** [comment]
The test-case does not send the token back to the application in a header or form value, hence the error.

**Comment by elithrar** [comment]
Hey @sprt - are you still having issues?

**Comment by sprt** [comment]
Hey sorry, nope, it was my mistake obviously!
