### ISSUE TITLE
Using http.Request.Context breaks compatibility with gorilla/mux

### ISSUE THREAD

**Issue by muirrn** [gorilla/csrf#45]
Using http.Request.Context() in this package breaks compatibility with any other code that uses gorilla/context (e.g. gorilla/mux). http.Request.WithContext() makes a new http.Request object, which messes up gorilla/context since gorilla/context stores its context values by the *http.Request pointer.

Seems like my only option is to use an older version of gorilla/csrf?

**Comment by elithrar** [comment]
Yes, unfortunately. gorilla/context and *any* package in Go 1.7 that calls `http.Request.WithContext()` will break gorilla/context, so you'll need to either use an older gorilla/csrf, or (preferably) update the other code.
