### ISSUE TITLE
Fixed: Forbidden - CSRF token invalid

### ISSUE THREAD

**Issue by 1046102779** [gorilla/csrf#47]
Cause: you use http not https to send request
Fixed: if you use http to send request,  you need modify a line of code
Steps：
1. "github.com/gorilla/csrf/options.go: 118 line
2. modify "cs.opts.Secure = true" to "cs.opts.Secure = false" 
3. go build && go install  , then your project will be  ok

**Comment by elithrar** [comment]
You don't have to modify any code at all. See the documentation for https://godoc.org/github.com/gorilla/csrf#Secure

If you aren't using HTTPS, CSRF protection is only a small help.
