### ISSUE TITLE
SPA cookie expire question

### ISSUE THREAD

**Issue by russtone** [gorilla/csrf#52]
Hi, I'm using your framework to protect REST API which I use from React SPA. I've read from other issues you recommend to put CSRF token to `<meta>` tag of index.html. So I have a question: How will my SPA get new CSRF token when the first one from `<meta>` tag is expired?

**Comment by elithrar** [comment]
How long-lived is an instance of your application? Unless the user never closes the browser tab, this shouldn't be a problem. You can also extend the expiry of the token as needed.

**Comment by russtone** [comment]
Ok, I think I'll extend expiry of token. Thanks for help!
