### ISSUE TITLE
Getting "nil" forbidden reason

### ISSUE THREAD

**Issue by philipithomas** [gorilla/csrf#53]
On a POST request, I'm getting a "nil"  forbidden reason. I've been trying to debug this for days, and I can't figure it out. It's only in our production environment. I can't reproduce in staging. A signing token of 32 bytes is set. The system panics if the signing token is zero length. 

```
Forbidden - %!s(<nil>)
```

Here's my config:

```
	CSRF := csrf.Protect(
		[]byte(signingToken),
		csrf.Domain(config.ExternalApex), // will be staffjoy.com
		csrf.Secure(!config.Debug), // Will be "true" in prod
		csrf.Path("/"), // I did this because I suspected 
		//csrf.ErrorHandler(http.HandlerFunc(func(res http.ResponseWriter, req *http.Request) {
		//	logger.Infof("failed CSRF - %s", csrf.FailureReason(req))
		//	errorpages.Forbidden(res)
		//})),
		csrf.FieldName("csrf"),
	)
```

Production page with the error is https://www.staffjoy.com/ with the path `/early-access/`. Other paths seem unaffected (hence my modification of `csrf.Path`). 

Any ideas?

**Comment by philipithomas** [comment]
I updated the version of CSRF and it started giving an error. I suspect that it was a go 1.7 issue.

**Comment by elithrar** [comment]
Yes, if you were using the new request context with older CSRF, the context
was dropped due to changes in Go and incompatibility with gorilla/context.

**Comment by kujenga** [comment]
@elithrar would you be able to put out a new release version with the fixes for this issue that are on master?

**Comment by elithrar** [comment]
@kujenga https://github.com/gorilla/csrf/releases/tag/v1.5 - done. Note that master is deemed API-stable as well, so you can always pull from master/update your vendored dependencies and re-run your builds against master.

(Pinning to versions in Go is problematic because there's not a single good solution/approach, yet)

**Comment by kujenga** [comment]
Great, thank you!

Yeah, we use glide as a package manager (which is great!) and they recently started pinning things to versions by default.
