### ISSUE TITLE
gorilla/csrf vs justinas/nosurf

### ISSUE THREAD

**Issue by dadatawajue** [gorilla/csrf#56]
Hi, I'm such a big fan of gorilla/sessions and securecookie.. in my previous project I've been using nosurf but I just discovered your csrf package..

Now I'm working on a new project using the pressly/chi router, and I was hoping you could share your expert opinion about whether any of these packages are more secure/performant than the other, or if it just comes down to personal taste?

**Comment by elithrar** [comment]
Both libraries are very similar in core behaviour. Most of the differences are around defaults & the APIs they expose.

* I wanted to support signed cookies (to prevent tampering) out of the box, and use the [securecookie](http://www.gorillatoolkit.org/pkg/securecookie) library for this. In reality, the benefits are minor: if you're not using TLS (HTTPS) already, then CSRF protection will only get you so far.
* Justinas' library has more fine-grained control around exempting specific paths based on exact matches, globs or regular expressions. I chose not to allow this as I saw the risk of messing up a pattern (and therefore accidentally not protecting routes you meant to protect) as too high, but have had requests to implement this. I can see the use cases here and understand why people would want this control.

**Comment by dadatawajue** [comment]
Thanks a lot <3

Regarding the second point (if I understand correctly), would it be possible to create a middleware handler:

```
func CSRFMiddleware(useHTTPS bool, key string) func(http.Handler) http.Handler {
  return csrf.Protect([]byte(key), csrf.Secure(useHTTPS))
} 
```

And then only use the CSRF middleware for certain routes (so in this example, only have CSRF protection for the `/register` path but not the `/about` path):

```
CSRF := CSRFMiddleware(viper.GetBoolean("https"), viper.GetString("csrfauthkey"))

r := chi.NewRouter()

r.Route("/register", func(r chi.Router) {
  r.Use(CSRF, OtherMiddleware)
  r.Get("/", controllers.RegisterGET))
})

r.Route("/about", func(r chi.Router) {
  r.Use(OtherMiddleware)
  r.Get("/", controllers.AboutGET))
})

http.ListenAndServe(":8080", r)
```
?

**Comment by elithrar** [comment]
Users can wrap this package like that, yes.

Note that in your example, there's no need to do that though: GET requests
aren't validated. Hence why it's usually safe to wrap your entire router.

**Comment by dadatawajue** [comment]
Oh yes, how stupid of me.. I still have a lot to read up on.. Thanks a lot for everything :)
