### ISSUE TITLE
How to update the secure cookie

### ISSUE THREAD

**Issue by gytibor** [gorilla/csrf#57]
Is there a way to update the secure cookie from the Go application after the Protect Function was called?

The authKey in my application can be changed by another go application, and I'd like to update the secure cookie to use the new authKey once my app realized that the authKey has been changed.
Restarting the whole HTTP server would be kind of difficult

Thank you

**Comment by elithrar** [comment]
There is not currently a way to rotate keys, but I could expose a
csrf.RotatedKeys(keys []byte...) function.

Note that this would work by passing the additional keys to the underlying
securecookie implementation, but has a catch: any unsuccessful decode will
fall through to the next key. You should thus be wary about leaving too
many keys in as it will have a performance impact (in-line with how often
you are rotating).

It should be clear that this won't directly resolve your use-case: you
actually want some form of atomic swap that replaces the in-use key *and*
re-initializes the underlying securecookie instance. Any existing cookies
would then be immediately invalid and it would need a mutex to prevent data
races.

(I'm not sure that's a simple solution that befits this library. What is
the purpose of changing keys "while running" - ?)

**Comment by gytibor** [comment]
Thank you for the quick answer.

This is in a multi process environment, where one process generates the authKey and other processes use the same authKey to use the same CSRF token for authentication.
The problem is if the key generator process gets restarted than it will generate a new key and the other already running processes will use the old key. As a result the client interface will fail the authentication, because it gets the updated cookie from the key generator process, but the other service will not recognize the new CSRF token.

This does not happen frequently, so I would not worry about to many keys ending up in the cookie, but it is not that simple as you wrote.

So maybe it is better if I tear down the http server and restart it when the new key is generated.
