### ISSUE TITLE
Forbidden - CSRF token invalid when using curl

### ISSUE THREAD

**Issue by deltaskelta** [gorilla/csrf#58]
I am in a dev environment and I am trying to play around with the middleware to get it to validate with curl but I cannot do it. I may be missing something simple.

```
var (
	CSRF = csrf.Protect(
		[]byte(`secret--secret--secret--secret--`),
		csrf.Secure(false),
		csrf.CookieName("csrf"),
	)
)

// using a library called alice to add middlewares...
	// Giving the routes a chain of middleware
	r = alice.New(
		context.ClearHandler,       // clears gorilla sessions memory leak
		handlers.RecoveryHandler(), // recovers from panics
		h.Sessions,                 // for tracking user sessions
		CSRF,                       // adding CSRF protection to responses
		h.Common,                   // adds common headers, other random things
	).Then(r)
```

if I first do a regular curl to a page I get...

```
~$ curl -vX GET 127.0.0.1:8080/user/dashboard --cookie "session=MTQ4OTQ4Mjg3M3xTV0ZyckFyOVhWU3NuN2tWTzBkcEVoWWdnRGNpRmdRakNOUGtxUXF2WmxPOXJxejZPRVR5NlJLdk9LeXR6N183RV9EekpJZ0FqcmUzLU5HV3R3PT18YFar7QU2OgDFw9Bze35bOvPKQlINwGnU8Ct55VUeDZY="
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /user/dashboard HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.51.0
> Accept: */*
> Cookie: session=MTQ4OTQ4Mjg3M3xTV0ZyckFyOVhWU3NuN2tWTzBkcEVoWWdnRGNpRmdRakNOUGtxUXF2WmxPOXJxejZPRVR5NlJLdk9LeXR6N183RV9EekpJZ0FqcmUzLU5HV3R3PT18YFar7QU2OgDFw9Bze35bOvPKQlINwGnU8Ct55VUeDZY=
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Set-Cookie: csrf=MTQ4OTU2OTgzMnxJamxKYkVORU5tbFJTMVpFVDNoblMzSjJNRGRGVG1nNVFVdEdObVl5ZEd0aE4xQk5NRWhyVUdGQ1N6QTlJZ289fBVAyXeIJScwZd8vkCX7VMvHWzERDZA7PGmSZuUeeHms; HttpOnly
< Vary: Cookie
< Date: Wed, 15 Mar 2017 09:23:52 GMT
< Content-Length: 29
< 
{"response":"Hi There UserName"}
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
```

and then if I use the received CSRF token to add an `X-CSRF-Token` header it fails to validate...

```
~$ curl -vX POST http://127.0.0.1:8080/user/update --cookie "session=MTQ4OTQ4Mjg3M3xTV0ZyckFyOVhWU3NuN2tWTzBkcEVoWWdnRGNpRmdRakNOUGtxUXF2WmxPOXJxejZPRVR5NlJLdk9LeXR6N183RV9EekpJZ0FqcmUzLU5HV3R3PT18YFar7QU2OgDFw9Bze35bOvPKQlINwGnU8Ct55VUeDZY=" --header "X-CSRF-Token: csrf=MTQ4OTU2OTI0NHxJbVl5VXpCSVRVbEVPVTl4YTA1blNsRktXWFpwT0V4MWJrUmhURWQ2UzJaa1dHMDVNbEJEYXpaQ2RtczlJZ289fDH39yldTHauDN4dQ8LVTK93RUTWkWKrURIVjSxQHOZ3; HttpOnly"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> POST /user/update HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.51.0
> Accept: */*
> Cookie: session=MTQ4OTQ4Mjg3M3xTV0ZyckFyOVhWU3NuN2tWTzBkcEVoWWdnRGNpRmdRakNOUGtxUXF2WmxPOXJxejZPRVR5NlJLdk9LeXR6N183RV9EekpJZ0FqcmUzLU5HV3R3PT18YFar7QU2OgDFw9Bze35bOvPKQlINwGnU8Ct55VUeDZY=
> X-CSRF-Token: csrf=MTQ4OTU2OTI0NHxJbVl5VXpCSVRVbEVPVTl4YTA1blNsRktXWFpwT0V4MWJrUmhURWQ2UzJaa1dHMDVNbEJEYXpaQ2RtczlJZ289fDH39yldTHauDN4dQ8LVTK93RUTWkWKrURIVjSxQHOZ3; HttpOnly
> 
< HTTP/1.1 403 Forbidden
< Content-Type: text/plain; charset=utf-8
< Set-Cookie: csrf=MTQ4OTU2OTk1MnxJa3QxV25aVE4wOVljbE5PUjJWMWNtdExkamRJUkZCVFUzVXJRbHBrY3pKa1QwdHRNWFV4TkhkRGJXTTlJZ289fDuSrugP1Up8fqYml7YUtbnw5iMfZhKHobudL9LCly9x; HttpOnly
< X-Content-Type-Options: nosniff
< Date: Wed, 15 Mar 2017 09:25:52 GMT
< Content-Length: 31
< 
Forbidden - CSRF token invalid
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
```

I have tried all variations I could think of using `csrf=<token>; HttpOnly`, `<token>`, `csrf=<token>`, adding the csrf to the cookie header in the response, etc. Can you see any reason why this would not be working?

**Comment by elithrar** [comment]
The header is just `X-CSRF-Token: <token>` - you don't use the cookie name or attributes.

**Comment by deltaskelta** [comment]
yes I tried that as well. I found two more things...

Sometimes the token contains `_` or `-` which gives an error in the `helpers.go` file when it is base64 decoding the string (`error: illegal base64 data at input byte 104`), so I must be doing something pretty wrong but I cannot see what it is. Other times when (by chance) it does not contain an illegal byte it still fails later in the process but I didn't have time to chase down where yet...

for reference, this is what the token looks like... 

`MTQ4OTU4MzQ2MXxJall4TUVwTlFXOTBNekJrVkZBeFIxWXhURGxCUlc1R2JWQm1VRUpUWW1kU05XSjVWRVZMTWtNek5WRTlJZ289fIFGGNLuIzcagsMWrYBD9OUYMtcoF0yGztmW8kIy0v_S`

does that seem to be correct? why would it sometimes have that illegal `_`?

**Comment by elithrar** [comment]
We use base64.StdEncoding, and so - and _ are not valid - they should
instead be + and /

Can you share your application code and how you are using this?

**Comment by elithrar** [comment]
Ignore that, I see what you're doing - 

* You're providing the *encoded cookie value* back to the library. The cookies are not the same as the tokens: the cookies are authenticated (HMAC) and encoded via securecookie
* If you are making a non-idempotent request back to the application, just include the cookie. Do not include the header as well - that's not necessary.

Just follow the example here https://github.com/gorilla/csrf#html-forms or use `--cookie` only in cURL.

**Comment by deltaskelta** [comment]
ok, I knew it was something basic and simple I was doing wrong but couldn't see. I actually decided to go with the JSON Web Token route with my API but thanks for your help, I love gorilla tools!
