### ISSUE TITLE
ErrBadToken when rebuilding docker container

### ISSUE THREAD

**Issue by jmackie4** [gorilla/csrf#70]
Apologies if this description is a bit lacking, but after hours of trying to debug this my head is fried and I'm none the wiser...

I'm running a simple server, in a docker container, on digital ocean. 

First deployment went great: CSRF middleware worked as intended without issues!

I then fixed a bug, rebuilt the container, pushed it to the server, and now any request going through the middleware is returning `ErrBadToken`. Nothing has changed as far as the `gorilla/csrf` code is concerned.

Clearing browser cookies doesn't fix it, restarting the browser doesn't fix it, but running in a Chrome incognito browser window does fix it. 

Note that I can't expect clients to clear their browser cache every time I push a new build.

Any suggestions? I'm hoping there is an obvious fix here that I'm missing. 

Thanks!

**Comment by elithrar** [comment]
How are you generating keys? Are you generating a key on build?

**Comment by jmackie4** [comment]
Nope, key is hardcoded.

The only clue I can offer is that it works fine when browsing Chrome incognito. Nothing else I've tried (which is a lot) has worked. Maybe the issue is with Chrome? 

If it is a Chrome issue I'd appreciate any suggestion as to how I might override it via the server?

**Comment by elithrar** [comment]
Can you provide a reproduction?

- Code?
- Docker image?
- site I can test against?

I run Chrome dev channel and don’t see problems.

**Comment by jmackie4** [comment]
I can try and make a reproducible example, but it would be tricky to give you direct access to the site. To reproduce it myself I do something like... 

Login -> ok

(rebuild container -> push to docker-machine)

Login -> ErrBadToken


I appreciate that may not be very helpful. But surely it must be down session data being cached somewhere? Is there anything you can suggest, before I tackle the nontrivial task of writing a reproducible example?

**Comment by elithrar** [comment]
Can you at least share your router code / where you instantiate
gorilla/csrf?

**Comment by jmackie4** [comment]
Sure, it boils down to something like...

```
package main

import (
	"log"
	"net/http"
	"strings"
	"time"

	"github.com/gorilla/csrf"
	"github.com/unrolled/secure"
)

func main() {
	r := http.NewServeMux()

	// Define handlers on r...

	secureMiddleware = secure.New(secure.Options{
		AllowedHosts:         []string{host},
		HostsProxyHeaders:    []string{"X-Forwarded-Host"},
		SSLRedirect:          true,
		SSLHost:              host,
		SSLProxyHeaders:      map[string]string{"X-Forwarded-Proto": "https"},
		STSSeconds:           315360000,
		STSIncludeSubdomains: true,
		STSPreload:           true,
		FrameDeny:            true,
		ContentTypeNosniff:   true,
		BrowserXssFilter:     true,
		ContentSecurityPolicy: strings.Join([]string{
			"default-src 'self'",
			"style-src 'self' 'unsafe-inline' https://fonts.googleapis.com/css",
			"font-src 'self' https://fonts.gstatic.com/",
			"img-src * 'self' data: https:",
			"connect-src 'self' wss://" + host + ":*",
		}, "; "),

		IsDevelopment: developing,
	}).Handler

	csrfMiddleware = csrf.Protect(
                []byte{...},  // hardcoded
		csrf.Secure(true),
	)

	srv := &http.Server{
		Handler: secureMiddleware(csrfMiddleware(r)),
		Addr:    ":" + port,

		// tlsConfig just defines GetCertificate
		TLSConfig: tlsConfig,

		WriteTimeout: 15 * time.Second,
		ReadTimeout:  15 * time.Second,
	}
	err := srv.ListenAndServeTLS(certFile, keyFile)
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by jmackie4** [comment]
So this turned out to be an issue related to the fact I had two apps running on different subdomains (but same top level domain) using the above code.

Explicitly setting the domain and path options in `csrf.Protect` seems to have fixed it.

**Comment by elithrar** [comment]
Glad to hear you fixed it + thanks for describing for future users!
