### ISSUE TITLE
CSRF token invalid on path prefix "/ru/..." in Chrome

### ISSUE THREAD

**Issue by dnx2k** [gorilla/csrf#72]
Completely having no ideas whats going on. If path of form begins with "/ru/..." I've got an error while posting data. Maybe this somehow relates to current locale, but this behavior seems weird. Firefox has no such issues.

```golang
package main

import (
    "fmt"
    "html/template"
    "net/http"

    "github.com/gorilla/csrf"
    "github.com/gorilla/mux"
)

var form = `
<html>
<head>
<title>Sign Up!</title>
</head>
<body>
<form method="POST" action="/signup/post" accept-charset="UTF-8">
<input type="text" name="name">
<input type="text" name="email">
<!--
The default template tag used by the CSRF middleware .
This will be replaced with a hidden <input> field containing the
masked CSRF token.
-->
{{ .csrfField }}
<input type="submit" value="Sign up!">
</form>
</body>
</html>
`

var t = template.Must(template.New("signup_form.tmpl").Parse(form))

func main() {
    r := mux.NewRouter()
    r.HandleFunc("/signup", ShowSignupForm)                // OK
    r.HandleFunc("/en/account/signup", ShowSignupForm)     // OK
    r.HandleFunc("/ru/account/signup", ShowSignupForm)     // FAIL! Forbidden - CSRF token invalid
    r.HandleFunc("/r/account/signup", ShowSignupForm)      // OK
    r.HandleFunc("/rus/account/signup", ShowSignupForm)    // OK
    r.HandleFunc("/ro/account/signup", ShowSignupForm)     // OK
    r.HandleFunc("/account/ru/signup", ShowSignupForm)     // OK
    // All POST requests without a valid token will return HTTP 403 Forbidden.
    r.HandleFunc("/signup/post", SubmitSignupForm)

    // Add the middleware to your router by wrapping it.
    http.ListenAndServe(":8000",
    csrf.Protect([]byte("32-byte-long-auth-key"))(r))
    // PS: Don't forget to pass csrf.Secure(false) if you're developing locally
    // over plain HTTP (just don't leave it on in production).
}

func ShowSignupForm(w http.ResponseWriter, r *http.Request) {
    // signup_form.tmpl just needs a {{ .csrfField }} template tag for
    // csrf.TemplateField to inject the CSRF token into. Easy!
    t.ExecuteTemplate(w, "signup_form.tmpl", map[string]interface{}{
        csrf.TemplateTag: csrf.TemplateField(r),
    })
}

func SubmitSignupForm(w http.ResponseWriter, r *http.Request) {
    // We can trust that requests making it this far have satisfied
    // our CSRF protection requirements.
    fmt.Fprintf(w, "%v\n", r.PostForm)
}
```

**Comment by dnx2k** [comment]
Very strange, being uploaded on real server there is no such a problem, only on localhost

**Comment by elithrar** [comment]
If you issue the cookie on the /signup path but then want to use it
elsewhere, you need to set csrf.Path to “/“ - otherwise the cookie is
scopes to the path If is issued on.

**Comment by dnx2k** [comment]
Thank you for your clues, that's make sence, I've tested this many times in incognito mode and results indeed different if i'm usgin different starting points. But I'm not writing any special cookies in this example, thats just as simple as above and still it works poorly. And if I use some simple paths like /subscribe there are no problems at all. What is a best practive for "resetting" of csrf? I've not found anything in the docs regardin this.

**Comment by dnx2k** [comment]
So in general problem is definitely not related to /ru/ but what's the best practice for rather simple case: navigation with laguage prefix if i want to switch language?

/en/something/...
/fr/someting/...

/fr/login

Login should be strictly at the root?

/login

And no other options?

**Comment by elithrar** [comment]
Use csrf.Path to set the cookie path to “/“.

https://godoc.org/github.com/gorilla/csrf#Path

**Comment by dnx2k** [comment]
Many thanks, hope this will be useful thread anyway.
