### ISSUE TITLE
Support for more 'safe' methods

### ISSUE THREAD

**Issue by pkaeding** [gorilla/csrf#74]
The [HTTP method registry](https://www.iana.org/assignments/http-methods/http-methods.xhtml) lists more 'safe' methods than those specified in RFC7231 (mostly from WebDAV).

While WebDAV may be dead, we find ourselves wanting a safe method that supports a request body. `REPORT` fits this bill nicely.  However, the list of [safe methods](https://github.com/gorilla/csrf/blob/master/csrf.go#L34) is inflexible, and this [appears to be by design](https://github.com/gorilla/csrf#design-notes) (which is why I'm opening an issue for discussion, rather than a PR with the change I'm suggesting).

What do you think about either:
* adding all safe methods from the HTTP method registry to the whitelist
* making the whitelist configurable/extendable

My first thought for a workaround was to call `csrf.UnsafeSkipCheck(r)` in a wrapper around the call to `csrf.Protect` when I detect the method is `REPORT`, but that didn't seem to work. When the `csrf.Protect` middleware ran, it [did not find the `skipCheckKey` on the context](https://github.com/gorilla/csrf/blob/master/csrf.go#L181). It is possible I was doing something wrong, though.

The workaround I settled on was to pretend `REPORT` was not safe, and require the CSRF token. This seems to work, but it strikes me as wrong.

**Comment by elithrar** [comment]
Can you share your code to skip the check for REPORT? That should work.

I’m hesitant to provide too much built-in configuration around bypassing
any method, as those things tend to be foot-guns for the uneducated.

**Comment by elithrar** [comment]
Following up on this, I'd expect the following to work:

```go
func SkipCSRFForReport(h http.Handler) http.Handler {
    fn := func(w http.ResponseWriter, r *http.Request) {

        if r.Method == "REPORT" {
            // Remember: request contexts in Go's std. lib create a shallow copy of the *Request, so you need to set the request to the return value here, otherwise you will not see the context values.
            r = csrf.UnsafeSkipCheck(r)
        }

        // Call the next handler
        h.ServeHTTP(w, r)
    }

    return http.HandlerFunc(fn)
}

**Comment by pkaeding** [comment]
Ahh, your reminder comment clued me into the problem with my bypass check. I thought I was mutating the right thing when I called `UnsafeSkipCheck`. After fixing that, everything works as I'd expect.

Thanks!

**Comment by elithrar** [comment]
Glad you got it working! 🙌🏼
