### ISSUE TITLE
Ability to manually expire cookie

### ISSUE THREAD

**Issue by kujenga** [gorilla/csrf#76]
In response to things like a user logout, I believe that it makes sense to expire the CSRF cookie in concert with others that were used for the login session.

Would it make sense for this library to provide a way to do that explicitly?

**Comment by elithrar** [comment]
As the CSRF cookie isn't directly tied to the login session, you shouldn't
have to explictly delete it (and unauthenticated forms may still need CSRF
protection).

I don't wholly object to a convenience method, but want to avoid too many
"options" as they introduce confusion/sharp edges.
