### ISSUE TITLE
Forbidden - CSRF token invalid

### ISSUE THREAD

**Issue by kaihendry** [gorilla/csrf#77]
Sorry for the support question here. I can't get it working. Can you see what I've done wrong here please?

https://s.natalian.org/2017-12-12/invalid.txt

**Comment by elithrar** [comment]
You also need to include the cookie: CSRF protection works via the
double-submit method, which is cookie + header or cookie + form value.

**Comment by kaihendry** [comment]
I tried 

    curl -i -X POST -H "X-CSRF-Token: D4y7rU3u6+r7dIVKKcIHXSijLNoZVFZzroo+WIIQHRqYsWI0JN/OH1ndMlwJNUsToyMYFsuYFoCdU9sTE0vpFg==" \
    > --cookie "_gorilla_csrf=MTUxMzA3NTA4NXxJbXg1VkdaT1puSTVLM2htUlZOSWVrcHVRa0V5UVVVMlVuTmtPRGh1TUc1WVMxTjZjRUp4ZGpCM01qZzlJZ289fGdyDFQVCXOviVwi4BUMHbyH5hdOt5jO1O80NiYKPAic" https://csrf.natalian.org

But it didn't appear to work either.

https://s.natalian.org/2017-12-13/1513127817_2548x1398.png

Why double submit? Seems a bit overkill!

**Comment by elithrar** [comment]
Hi @kaihendry - "double submit" isn't overkill, it's how CSRF prevention works: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Double_Submit_Cookie without additional application logic to tie token <-> user. This is the same approach used by major web frameworks like Rails & Django, so it's a well-tested approach to making CSRF protection accessible and usable.

Here's a working example against your test server:

```
➜  ~  curl -i -X POST -H "X-CSRF-Token: j97aMuJj2ozO+5M/7y05ZW1F7BAjSwRXdcpoZvN8WaPFcp6YERypv6dFrdgMRXxfLmIkaFQTh91sSSDMUglg2g==" --cookie "_gorilla_csrf=MTUxMzEyODU2MnxJbE54ZUVWeGRrNHZZM3BPY0hacU4yNDBNbWhHVDJ0TmJubElhRE5YU1U5TFIxbE9TWEZ4UmpGUFdHczlJZ289fORCMPTrMcEAOXqP-BJeYpQyAaEyPUY4avwpURm2al-r" https://csrf.natalian.org
HTTP/2 200
content-type: text/plain; charset=utf-8
content-length: 6
date: Wed, 13 Dec 2017 01:31:03 GMT
x-amzn-requestid: 485de39e-dfa5-11e7-adae-4396a62ae150
x-amzn-remapped-content-length: 6
vary: Cookie
x-powered-by: up
x-amzn-trace-id: sampled=0;root=1-5a3082d7-ea9b7fe2fe5dc730b021e15a
x-amzn-remapped-date: Wed, 13 Dec 2017 01:31:03 GMT
x-cache: Miss from cloudfront
via: 1.1 d01884a3320364227d925bce1a38f0ad.cloudfront.net (CloudFront)
x-amz-cf-id: zieH0yz_x10GcBzO_fDuyuzOQAUVvAK4CKbDT4wc4NWNEm9WnYm6jA==

Oh hai% 
```

Note that the token and the cookie are related: if you are using an "old" cookie or token, and a different cookie, it won't work. Browsers don't have this issue as they remember the cookie appropriately.

**Comment by kaihendry** [comment]
Thanks. Perhaps my code here would be a good basis of an example?

https://s.natalian.org/2017-12-13/main.go

**Comment by kaihendry** [comment]
Oh, do you have an example where you read the header as you say here: "JavaScript framework can now read the header and return the token"?

It appears non-trivial to do this!

**Comment by mylons** [comment]
@elithrar i came across this having a similar misunderstanding. the final key to me understanding this is where are you getting the `X-CSRF-Token` and `_gorilla_csrf` cookie values you use in the working curl command?

**Comment by elithrar** [comment]
@mylons 

Slow reply, sorry:

* `X-CSRF-Token` can be provided in a response header: `w.Header().Set("X-CSRF-Token", csrf.Token(r))`
* `_gorilla_csrf` is automatically set in responses when you wrap your handlers with `csrf.Protect`

**Comment by elithrar** [comment]
@kaihendry @mylons The README covers the Go side: https://github.com/gorilla/csrf#javascript-applications

Your JavaScript application may want to fire an XHR request early, get the cookie (automatic, if you have wrapped all routes), and then store the X-CSRF-Token response header value in its local datastore, updating it as needed, and passing it as an additional request header on all outgoing requests.

**Comment by mylons** [comment]
@elithrar cheers!
