### ISSUE TITLE
middleware question 

### ISSUE THREAD

**Issue by ljesparis** [gorilla/csrf#78]
the doc says that i can use this middleware with gin framework, but how>?

**Comment by hongjinlin** [comment]
how?

**Comment by fmpwizard** [comment]
this shows the options you have
https://github.com/gin-gonic/contrib/issues/63

**Comment by rickwang7712** [comment]
I have tried this way, and it seems to work fine. 
However, I'm just a beginner. Maybe there is some problem that I haven't discovered...

Use CSRF() as normal gin middleware, you can pass to group or router like 
"xxx.Use(middlewares.CSRF())".

```
package middlewares

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/gorilla/csrf"
	adapter "github.com/gwatts/gin-adapter"
)

var csrfMd func(http.Handler) http.Handler

func init() {
	csrfMd = csrf.Protect([]byte("Taiwan is NOT part of China."),
		csrf.MaxAge(0),
		csrf.Secure(true),
		csrf.ErrorHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusForbidden)
			w.Write([]byte(`{"message": "Forbidden - CSRF token invalid"}`))
		})),
	)
}

func CSRF() gin.HandlerFunc {
	return adapter.Wrap(csrfMd)
}
```

**Comment by elithrar** [comment]
@rickwang7712 0- I don't see any issue with your code there - `adapter.Wrap` is what Gin provides to leverage `http.Handler` implementations instead of Gin-specific types.

**Comment by elithrar** [comment]
(Updated the title to be more searchable against Gin or gin-gonic)
