### ISSUE TITLE
complete example

### ISSUE THREAD

**Issue by proclaim** [gorilla/csrf#80]
I can't quite get the example to work, and I keep getting Forbidden - CSRF token invalid. I'm using HTML form as illustrated and I did see an hidden input field of gorilla.csrf.Token with its value.

am I missing something? can there be a complete example? thank you~

ps. I even tried the example here:
http://www.gorillatoolkit.org/pkg/csrf

**Comment by elithrar** [comment]
Can you share what you’ve tried so far?

**Comment by proclaim** [comment]
here's what I used following the guide from http://www.gorillatoolkit.org/pkg/csrf

```
package main

import (
    "fmt"
    "html/template"
    "net/http"

    "github.com/gorilla/csrf"
    "github.com/gorilla/mux"
)

var form = `
<html>
<head>
<title>Sign Up!</title>
</head>
<body>
<form method="POST" action="/signup/post" accept-charset="UTF-8">
<input type="text" name="name">
<input type="text" name="email">
<!--
The default template tag used by the CSRF middleware .
This will be replaced with a hidden <input> field containing the
masked CSRF token.
-->
{{ .csrfField }}
<input type="submit" value="Sign up!">
</form>
</body>
</html>
`

var t = template.Must(template.New("signup_form.tmpl").Parse(form))

func main() {
    r := mux.NewRouter()
    r.HandleFunc("/signup", ShowSignupForm)
    // All POST requests without a valid token will return HTTP 403 Forbidden.
    r.HandleFunc("/signup/post", SubmitSignupForm)

    // Add the middleware to your router by wrapping it.
    http.ListenAndServe(":8000",
    csrf.Protect([]byte("32-byte-long-auth-key"))(r))
    // PS: Don't forget to pass csrf.Secure(false) if you're developing locally
    // over plain HTTP (just don't leave it on in production).
}

func ShowSignupForm(w http.ResponseWriter, r *http.Request) {
    // signup_form.tmpl just needs a {{ .csrfField }} template tag for
    // csrf.TemplateField to inject the CSRF token into. Easy!
    t.ExecuteTemplate(w, "signup_form.tmpl", map[string]interface{}{
        csrf.TemplateTag: csrf.TemplateField(r),
    })
}

func SubmitSignupForm(w http.ResponseWriter, r *http.Request) {
    // We can trust that requests making it this far have satisfied
    // our CSRF protection requirements.
    fmt.Fprintf(w, "%v\n", r.PostForm)
}
```

put that in main.go and run from there. execute with go run main.go and nagivate to localhost:8000/signup
after I click submit it says "Forbidden - CSRF token invalid"

thanks for the help!

**Comment by elithrar** [comment]
Did you set Secure(false) as per the example? I assume you’re running this
locally without SSL?

// PS: Don't forget to pass csrf.Secure(false) if you're developing locally
// over plain HTTP (just don't leave it on in production).

**Comment by proclaim** [comment]
Yes, I did try that, I put
`csrf.Secure(false)` right above `http.ListenAndServe(":8000", csrf.Protect([]byte("32-byte-long-auth-key"))(r))`
still no luck =(

**Comment by elithrar** [comment]
- How are you making requests? Browser? Curl
- Does your browser have the cookie?
- What’s the path on that cookie? Can you see the cookie in the Web
Inspector?

**Comment by proclaim** [comment]
I am using chrome 63, and I did see cookie csrf_token from the developer tools (`xFI4ga8nGODJKfilOUVYrIqxE/vm8FF3poh7xYJeqjE=`)

**Comment by proclaim** [comment]
ok, after I did some trace, I think the cookie is not successfully set (although the web browser does support cookie) let me do more investigation

**Comment by proclaim** [comment]
seems like I'm unable to set cookies. (checked with Chrome, IE and Firefox) and that's causing this problem.

I use [this example](https://gist.github.com/liubin/5705616) for cookie test and was able to see the cookie though.

something is not right, can any verify this?

put the following code in `main.go` and run `go run main.go`?

```
package main

import (
    "fmt"
    "html/template"
    "net/http"

    "github.com/gorilla/csrf"
    "github.com/gorilla/mux"
)

var form = `
<html>
<head>
<title>Sign Up!</title>
</head>
<body>
<form method="POST" action="/signup/post" accept-charset="UTF-8">
<input type="text" name="name">
<input type="text" name="email">
<!--
The default template tag used by the CSRF middleware .
This will be replaced with a hidden <input> field containing the
masked CSRF token.
-->
{{ .csrfField }}
<input type="submit" value="Sign up!">
</form>
</body>
</html>
`

var t = template.Must(template.New("signup_form.tmpl").Parse(form))

func main() {
    r := mux.NewRouter()
    r.HandleFunc("/signup", ShowSignupForm)
    // All POST requests without a valid token will return HTTP 403 Forbidden.
    r.HandleFunc("/signup/post", SubmitSignupForm)

    // Add the middleware to your router by wrapping it.
    http.ListenAndServe(":8000",
    csrf.Protect([]byte("32-byte-long-auth-key"))(r))
    // PS: Don't forget to pass csrf.Secure(false) if you're developing locally
    // over plain HTTP (just don't leave it on in production).
}

func ShowSignupForm(w http.ResponseWriter, r *http.Request) {
    // signup_form.tmpl just needs a {{ .csrfField }} template tag for
    // csrf.TemplateField to inject the CSRF token into. Easy!
    t.ExecuteTemplate(w, "signup_form.tmpl", map[string]interface{}{
        csrf.TemplateTag: csrf.TemplateField(r),
    })
}

func SubmitSignupForm(w http.ResponseWriter, r *http.Request) {
    // We can trust that requests making it this far have satisfied
    // our CSRF protection requirements.
    fmt.Fprintf(w, "%v\n", r.PostForm)
}
```

**Comment by elithrar** [comment]
Can you answer all of the below questions:

- Can you share the full cookie parameters - in the Set-Cookie response
header - as seen in the browser?

- Are you making all requests via a browser?

- Did you set Secure(false) as per the comment in the example?

**Comment by proclaim** [comment]
sorry for not making things clear, here are the final code that I use in `main.go`

```
package main

import (
	"fmt"
	"html/template"
	"net/http"

	"github.com/gorilla/csrf"
	"github.com/gorilla/mux"
)

var form = `
<html>
<head>
<title>Sign Up!</title>
</head>
<body>
<form method="POST" action="/signup/post" accept-charset="UTF-8">
<input type="text" name="name">
<input type="text" name="email">
<!--
The default template tag used by the CSRF middleware .
This will be replaced with a hidden <input> field containing the
masked CSRF token.
-->
{{ .csrfField }}
<input type="submit" value="Sign up!">
</form>
</body>
</html>
`

var t = template.Must(template.New("signup_form.tmpl").Parse(form))

func main() {
	r := mux.NewRouter()
	r.HandleFunc("/signup", ShowSignupForm)
	// All POST requests without a valid token will return HTTP 403 Forbidden.
	r.HandleFunc("/signup/post", SubmitSignupForm)

	// Add the middleware to your router by wrapping it.
	csrf.Secure(false)
	http.ListenAndServe(":8000",
		csrf.Protect([]byte("32-byte-long-auth-key"))(r))
	// PS: Don't forget to pass csrf.Secure(false) if you're developing locally
	// over plain HTTP (just don't leave it on in production).
}

func ShowSignupForm(w http.ResponseWriter, r *http.Request) {
	// signup_form.tmpl just needs a {{ .csrfField }} template tag for
	// csrf.TemplateField to inject the CSRF token into. Easy!
	t.ExecuteTemplate(w, "signup_form.tmpl", map[string]interface{}{
		csrf.TemplateTag: csrf.TemplateField(r),
	})
}

func SubmitSignupForm(w http.ResponseWriter, r *http.Request) {
	// We can trust that requests making it this far have satisfied
	// our CSRF protection requirements.
	fmt.Fprintf(w, "%v\n", r.PostForm)
}
```

2. `go run main.go`
3. open chrome and fire the request `localhost:8000/signup`
4. (see attached image)
<img width="1132" alt="image1" src="https://user-images.githubusercontent.com/2252778/35919984-81cd5140-0c51-11e8-9a78-afa18e31807c.png">
<img width="1131" alt="image2" src="https://user-images.githubusercontent.com/2252778/35919983-81a519f0-0c51-11e8-911a-e80ffb6279fc.png">
5. enter some value in two textbox and then submit
6. 
<img width="1137" alt="image3" src="https://user-images.githubusercontent.com/2252778/35920117-f3b40042-0c51-11e8-9741-d562bd790fbb.png">

(I hope I didn't do something stupid)

**Comment by elithrar** [comment]
You're setting `csrf.Secure(false)` outside of the `csrf.Protect` instance: your cookies still have the Secure flag. As you're accessing the page over plaintext HTTP, the cookie is not being sent back on each request.

You want:
```go
http.ListenAndServe(":8000",
		csrf.Protect(
				[]byte("32-byte-long-auth-key"),
				csrf.Secure(false), // Pass it *to* this constructor
		)(r))
```

**Comment by proclaim** [comment]
that's it! thank you so much and please forgive my ignorance. =)

**Comment by elithrar** [comment]
No problems! Glad it works.
