### ISSUE TITLE
[question] Apply CSRF only to a subrouter

### ISSUE THREAD

**Issue by karel-3d** [gorilla/csrf#85]
I don't understand how to apply CSRF only to one subrouter.

Example, from the example in the doc:

````go
    r := mux.NewRouter()

    sr1 := r.PathPrefix("/api1").Subrouter()
    sr1.HandleFunc("/user/{id}", ApiFunc).Methods("GET")

    sr2 := r.PathPrefix("/api2").Subrouter()
    sr2.HandleFunc("/user/{id}", AnotherApiFunc).Methods("GET")

    // I want to protect only sr1, not sr2. How to do it?
    http.ListenAndServe(":8000",
        csrf.Protect([]byte("32-byte-long-auth-key"))(r))
````

**Comment by karel-3d** [comment]
.....maybe `sr2.Use(csrf.Protect([]byte("32-byte-long-auth-key")))`?

**Comment by elithrar** [comment]
Best practice is to instantiate a new CSRF instance and then .Use() that as
needed:

csrfMiddleware := csrf.Protect(key, options)

sr2.Use(csrfMiddleware)

This allows you to use the same instance across multiple subrouters, rather
than re-initializing it each time.

**Comment by elithrar** [comment]
(Closing for now, but reply here if any more questions!)

**Comment by karel-3d** [comment]
This worked. Thanks, and thanks for all the libraries :)
