### ISSUE TITLE
Forbidden - CSRF token invalid 

### ISSUE THREAD

**Issue by maxdobeck** [gorilla/csrf#86]
Hi I'm getting a Forbidden "token invalid" 403 response even though the token is correct.

Here I'm setting the token in my store when the app loads:
```javascript
    function () {
      fetch(apiURL, {
        method: 'GET'
      })
        // .then(response => console.log(response.headers.get('X-CSRF-Token')))
        .then(response => this.setCSRFToken(response.headers.get('X-CSRF-Token')))
    }
```

Here I'm sending a POST request (along with the gorilla_csrf cookie) from the domains /login route.
```javascript
      fetch(apiURL, {
        method: 'POST',
        credentials: 'include',
        headers: {
          'X-CSRF-Token': this.token
        },
```
Here's the Request being sent:
```
x-csrf-token: fzMz+oxy0boOITi1GwX36Jq9zhIIp5Zcy30B6gAucyDCsbWc7D7ysHezSq7qD61iAj6sMoz+uUmymMZJ8jE5+Q==
content-type: text/plain;charset=UTF-8
origin: http://localhost:3030
Content-Length: 51
Cookie: _gorilla_csrf=MTUyODA1MjI5M3xJbTVTYWxCbGJuUk1VWGQzYVM4Mll6WmhRbXBKVDNOMFVrRXlaVVZ2VEM4MVNGSjRWbmwwV1hCcFpUZzlJZ289fJPKHLOD_-ckXHtzjS04npF3SEc0usqBDJl8COBW6XZc; scheduler-session=MTUyODA3MDExOHxOd3dBTkZWRFNUWkRUMU5YTlZGSFQwRkRWVVpTVkU5Q1RrMUtTRlpJU1VST1NrMVRTRkJPUjFCVlVWRlFNMW8wUmxOV1JGbEVTbEU9fBMnxfc2ZqhJtakQ_RS316Uu_ACUk1Xv-Nz0LLd8gxPK
```

Is there additional debugging or output I can enable to help troubleshoot?

**Comment by maxdobeck** [comment]
Figured it out!  I found out that I was getting a new cookie on every single route I was hitting.  So the token + cookie were mismatched.

Between Postman and Dev tools I realized I needed to add the `credentials: 'include'` in the fetch request.

Changed my app's initial token setting function to this and all is well:
```javascript
 function () {
      fetch(apiURL, {
        method: 'GET',
        credentials: 'include'
      })
        // .then(response => console.log(response.headers.get('X-CSRF-Token')))
        .then(response => this.setCSRFToken(response.headers.get('X-CSRF-Token')))
    }
```

**Comment by elithrar** [comment]
Glad you figured it out, and thanks for documenting it here such that
others may stumble across it!

**Comment by misterr8472** [comment]
My dear sir, you just ended three days of pain. Thank you, thank you, thank you.
