### ISSUE TITLE
Interaction with Websockets 

### ISSUE THREAD

**Issue by iaburton** [gorilla/csrf#92]
Hey there! Quick question, is there anyway to force the middleware (or via some other method) to check a GET request if it is for a websocket handshake?

I was reading, http://www.christian-schneider.net/CrossSiteWebSocketHijacking.html and it seems like if you already have CSRF values in the request you can use that as long as you check them. But since the handler doesn't check the token on GET requests I was wondering if there was a way to do this? Or maybe there is a better way to handle websocket connections all together? My application has normal REST and a websocket endpoint, and I'll be using the gorilla/websocket package which I know checks the Origin header by default. Thanks

**Comment by elithrar** [comment]
Best practice (and the most effective thing to do) is to check the Origin
header. Adding CSRF protection after that is redundant, since checking the
Origin prevents the "Cross Site" part of CSRF.

(gorilla/websocket is a good package to use!)

**Comment by iaburton** [comment]
Sweet. I had been using websockets for a while in different languages (thank you guys for all the great packages btw) and thought I was doing something wrong, I knew about the Origin check but after reading that article wasn't sure if I needed to be doing both. Thanks for the sanity check!
