### ISSUE TITLE
Forbidden - CSRF token invalid

### ISSUE THREAD

**Issue by nanohayder** [gorilla/csrf#93]
Hi
can you please help I'm always getting the error "Forbidden - CSRF token invalid" even though I have disabled the secure flag my code is below

```
CSRF := csrf.Protect(
		[]byte("08SY058118B4DN7adZr5a77Omvp6v1vA"),
		csrf.FieldName("authenticity_token"),
		csrf.Secure(false),
		csrf.HttpOnly(false),
		csrf.Path("/"),
		csrf.MaxAge(12000),
	)
	mux.HandleFunc("/login", login)
	mux.HandleFunc("/todo", todo)
	mux.HandleFunc("/listDevices", listDevices)
	mux.Handle("/assets/", &logServer{
		http.StripPrefix("/assets/", http.FileServer(http.Dir("assets/"))),
	})
	mux.Handle("/Clients/", &logServer{
		clientConfig(http.StripPrefix("/Clients/", http.FileServer(http.Dir("Clients/")))),
	})
	mux.Handle("/tut/", &logServer{
		tutImages(http.StripPrefix("/tut/", http.FileServer(http.Dir("tut/")))),
	})
	mux.Handle("/", &logServer{
		noDirListing(http.FileServer(http.Dir("."))),
	})
	http.ListenAndServe(":8080", CSRF(mux))
```
my request headers are below:
Accept: text/html, */*; q=0.01
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ar;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 198
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: _gorilla_csrf=MTUyOTgzMzU5M3xJbmR2VkhRMWJrbEhVV3hhUlU1b2F5dFZOMkpLY0dsUmMyRTBOMjFRT0ZoM1kyMHhWSEJuV0ZOSFNUZzlJZ289fMv0K_iHYrxTr7pjDC6J5uZpxWjltzhssQhv8TCZ3duI
Host: localhost:8080
Origin: http://localhost:8080
Pragma: no-cache
Referer: http://localhost:8080/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
X-CSRF-Token: MTUyOTgzMzU5M3xJbmR2VkhRMWJrbEhVV3hhUlU1b2F5dFZOMkpLY0dsUmMyRTBOMjFRT0ZoM1kyMHhWSEJuV0ZOSFNUZzlJZ289fMv0K_iHYrxTr7pjDC6J5uZpxWjltzhssQhv8TCZ3duI
X-Requested-With: XMLHttpRequest

my form data are below
user: hayder.sinan
pass: *************
authenticity_token: MTUyOTgzMzU5M3xJbmR2VkhRMWJrbEhVV3hhUlU1b2F5dFZOMkpLY0dsUmMyRTBOMjFRT0ZoM1kyMHhWSEJuV0ZOSFNUZzlJZ289fMv0K_iHYrxTr7pjDC6J5uZpxWjltzhssQhv8TCZ3duI

can you please help?

**Comment by elithrar** [comment]
What path in your application is this being tested against?

**Comment by nanohayder** [comment]
It's being test on path /login

**Comment by nanohayder** [comment]
I tried two ways once I injected it in the html and read it in java script and send it using ajax

The second way which currently Im testing it is that Im using the same cookie value and send in the ajax so in go the only place csrf available is in the main function whic is the code I included earlier.

**Comment by elithrar** [comment]
You don't want to blindly copy the cookie value.

Call https://godoc.org/github.com/gorilla/csrf#Token and pass that in the
named form value (or use the template helper), or pass that in the header,
as per the examples.

**Comment by nanohayder** [comment]
Thank you so mush for your ans. I was completely on the wrong track and now everything is working just fine 

Thanks
