### ISSUE TITLE
How to do csrf protection for http.Get requests?

### ISSUE THREAD

**Issue by qibobo** [gorilla/csrf#95]
Currently the csrf protection will skip http Get requests in the code "if !contains(safeMethods, r.Method)".
In my application I want to some http Get requests to be protected, how to do it?

**Comment by elithrar** [comment]
Can you explain more about your application? What drives the need to
protect GET requests?

**Comment by qibobo** [comment]
@elithrar
There are some routes in the application:
/index http.Get
/getSomething http.Get
/putSomething http.Put

The "/index" route will return a web page that contains the csrf-token and users can request the "/getSomething" by csrf attack as no csrf protection for it, right? I want to protect the "/getSomething".

**Comment by elithrar** [comment]
That’s not how the protection works.

CSRF requires the attacker to make a mutating change. Tokens are always
issued regardless of method, but a GET should not make a change on behalf
of the user. This is why non-idempotent methods (POST, PUT, etc) use the
protection.

**Comment by qibobo** [comment]
@elithrar Got it. Thank you!
